services:
  postgres:
    image: postgres:latest
    container_name: null_void_postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - paytrail_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_123
      POSTGRES_DB: null_void_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  null_void_1:
    image: null_void_server:latest
    container_name: null_void_1
    restart: unless-stopped
    mem_limit: 512m
    volumes:
      - ./logs/null_void_1:/app/logs
    depends_on:
      - postgres
      - cache_redis
      - queue_redis
    networks:
      - paytrail_network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4000/health",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    env_file:
      - .env.server
    ports:
      - "4000:4000"

  null_void_2:
    image: null_void_server:latest
    container_name: null_void_2
    restart: unless-stopped
    mem_limit: 512m
    volumes:
      - ./logs/null_void_2:/app/logs
    depends_on:
      - postgres
      - cache_redis
      - queue_redis
    networks:
      - paytrail_network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5000/health",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    env_file:
      - .env.server
    ports:
      - "5000:4000"

  null_void_queue_processor:
    image: null_void_processor:latest
    container_name: null_void_queue_processor
    restart: unless-stopped
    volumes:
      - ./logs/null_void_queue_processor:/app/logs
    depends_on:
      - postgres
      - cache_redis
      - queue_redis
    networks:
      - paytrail_network
    env_file:
      - .env.processor

  cache_redis:
    image: redis:latest
    container_name: null_void_cache_redis
    networks:
      - paytrail_network
    volumes:
      - cache_redis_data:/data
      - "./cache-redis.conf:/etc/redis/redis.conf"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    mem_limit: 256m
    restart: unless-stopped

  queue_redis:
    image: redis:latest
    container_name: null_void_queue_redis
    networks:
      - paytrail_network
    volumes:
      - queue_redis_data:/data
      - "./queue-redis.conf:/etc/redis/redis.conf"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    mem_limit: 512m
    restart: unless-stopped

networks:
  paytrail_network:
    external: true
    name: system_wide_network

volumes:
  cache_redis_data:
  queue_redis_data:
  postgres_data:
