name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Processor Image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: apps/processor/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/null-void-processor:${{ github.sha }}, ${{ vars.DOCKERHUB_USERNAME }}/null-void-processor:latest
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/null-void-processor:buildcache
          cache-to: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/null-void-processor:buildcache,mode=max,push=true

      - name: Build and push Server Image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: apps/server/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/null-void-server:${{ github.sha }}, ${{ vars.DOCKERHUB_USERNAME }}/null-void-server:latest
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/null-void-server:buildcache
          cache-to: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/null-void-server:buildcache,mode=max,push=true

      - name: Copy Ops Files to Server
        uses: Burnett01/rsync-deployments@v8
        with:
          path: ./ops/
          switches: -avr --exclude=".git/*" --exclude=".env*"
          remote_host: ${{ secrets.HOSTNAME }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_path: /home/${{ secrets.REMOTE_USER }}/projects/null-void/

      - name: Start new containers
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.REMOTE_USER }}/projects/null-void/
            docker compose up -d
            echo "Successfully deployed to server"
